## -----------------------
##  BOOK PROJECT SETTINGS
## -----------------------

## -----------------------~~~~~~~~~~~~~~~
##  GLOBAL SETTIGNS
##    * Applied to all build-pipelines
## -----------------------~~~~~~~~~~~~~~~~

global:
  meta:
    title: The Global Title
    author: Iman Ahthur
    description: My book is amazing and stuff!
    isbn-13: 1234567891011
    isbn-10: 1234567891
    publisher: Global Settings Press
    date: 2013-03-31
    language: en
    subject: Non-fiction
    rights: All Rights Reserved
    copyright: © 2025
    subtitle: A Global Subtitle
    version: '1.0'
    lccn: 1234567891011

## Stage-specific global settings
  stages:
    - name: ejs
      config:
        entryfile: inddex.md.ejs
        rmWhitespace: true